name: SkyCounters
version: '${version}'
main: me.skyscx.skycounters.SkyCounters
api-version: '1.20'
commands:
  topmessages:
    description: View the top 10 players by message count
    usage: /topmessages