name: SkyCounters
version: '1.1'
main: me.skyscx.skycounters.SkyCounters
api-version: '1.20'
commands:
  topmessages:
    description: Список топа по популярным сообщениям
    usage: /topmessages
    aliases:
      - tm
      - topm
  scdelete:
    description: Удалить из таблицы игрока
    usage: /scdelete [name]
    aliases:
      - scd
      - scdel